// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       throw UnsupportedError(
//         'DefaultFirebaseOptions have not been configured for web - '
//         'you can reconfigure this by running the FlutterFire CLI again.',
//       );
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyA09oOMVS63J-gyKlk0TyHQDNWuzmbig0Q',
//     appId: '1:1057984911405:android:91b0cad28b61141e94c0a4',
//     messagingSenderId: '1057984911405',
//     projectId: 'foodly-flutter-dc94b',
//     databaseURL: 'https://foodly-flutter-dc94b-default-rtdb.firebaseio.com',
//     storageBucket: 'foodly-flutter-dc94b.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAxBpSy7vvZYMubU_FiEIsw0P9UaSBHfdM',
//     appId: '1:1057984911405:ios:87b1d0e22f2d4f5f94c0a4',
//     messagingSenderId: '1057984911405',
//     projectId: 'foodly-flutter-dc94b',
//     databaseURL: 'https://foodly-flutter-dc94b-default-rtdb.firebaseio.com',
//     storageBucket: 'foodly-flutter-dc94b.appspot.com',
//     androidClientId: '1057984911405-a22docs9mvhm8jocefp2caq1j1pjogg1.apps.googleusercontent.com',
//     iosClientId: '1057984911405-5iegqua3t9p44dkf6bhvnvolu10sff7v.apps.googleusercontent.com',
//     iosBundleId: 'com.example.foodly',
//   );
// }
